### ISSUE TITLE
vue-devtools production mode 

### ISSUE THREAD

**Issue by c01nd01r** [matheusazzi/shop-vue#1]
>Also I suggest you to use vue-devtools if you want a see how everything happens.

but: 
![Image of Yaktocat](http://storage7.static.itmages.ru/i/16/1123/h_1479908843_1554367_c7f002f438.png)

**Comment by matheusazzi** [comment]
@c01nd01r Ohh yeah, Vue Devtools won't work in production, but if you clone the repo and run it locally it'll work. 
Vuex debug is disabled in production to perform better. https://github.com/matheusazzi/shop-vue/blob/master/src/store/index.js#L12
