### ISSUE TITLE
I was trying for woocommerce plugin with vue js

### ISSUE THREAD

**Issue by niamrox** [matheusazzi/shop-vue#2]
I was trying for woocommerce plugin with vue js. Just add to cart option. Because woocommerce add to cart is slower than expected.

**Comment by matheusazzi** [comment]
It's just an static experiment with Vue.js and Vuex, it doesn't have any relation with woocommerce or anything. Sorry, I don't have experience with wordpress, so I can't indicate any plugin to help you with it.
